"use client";

/* eslint-disable jsx-a11y/label-has-associated-control -- controls use generated and explicit ids inside compact settings rows. */

import { Check, MessageSquareText, Sparkles, Star } from "lucide-react";
import type { StarboardSettings, SuggestionSettings } from "@/packages/core/src/domain";
import { DashboardShell } from "./dashboard-shell";
import { useGuildSettings } from "./use-guild-settings";

export function CommunityConfigPage({ guildId }: { guildId: string }) {
  const state = useGuildSettings(guildId);
  const suggestions: SuggestionSettings = { anonymous: false, createThreads: true, ...state.draft?.settings.suggestions };
  const starboard: StarboardSettings = { emoji: "⭐", threshold: 3, allowSelfStars: false, ignoredChannelIds: [], ...state.draft?.settings.starboard };
  const textChannels = state.resources?.channels.filter((channel) => [0, 5].includes(channel.type)) ?? [];
  const updateSuggestions = (patch: Partial<SuggestionSettings>) => state.updateSettings((settings) => ({ ...settings, suggestions: { ...settings.suggestions, ...patch } }));
  const updateStarboard = (patch: Partial<StarboardSettings>) => state.updateSettings((settings) => ({ ...settings, starboard: { ...settings.starboard, ...patch } }));

  return <DashboardShell guildId={guildId} guildName={state.guildName} active="community">
    <div className="page-heading"><div><span className="page-kicker">Member programs</span><h1>Community</h1><p>Give good ideas a workflow and memorable messages a permanent home.</p></div><div className="heading-stat"><Sparkles size={18} /><span><strong>2</strong> configurable programs</span></div></div>
    {state.error && <div className="error-banner">{state.error}</div>}
    {state.loading || !state.draft ? <div className="loading-stack">{[0,1].map((item) => <div className="skeleton" key={item} />)}</div> : <>
      {state.message && <div className={state.message.kind === "success" ? "success-banner" : "error-banner"}>{state.message.text}</div>}
      <div className="community-grid">
        <section className="settings-card community-card"><div className="feature-heading"><span className="feature-icon"><MessageSquareText size={21} /></span><div><span className="page-kicker">Idea pipeline</span><h2>Suggestions</h2></div></div><p>Members submit with <code>/suggest</code>. Staff can approve, deny, implement, or mark duplicates while the original post stays updated.</p><div className="field"><label htmlFor="suggestion-channel">Suggestion board</label><select id="suggestion-channel" className="select" value={suggestions.channelId ?? ""} onChange={(event) => updateSuggestions({ channelId: event.target.value || undefined })}><option value="">Choose a channel</option>{textChannels.map((channel) => <option key={channel.id} value={channel.id}>#{channel.name}</option>)}</select></div><div className="switch-list"><label className="switch-row" htmlFor="suggest-anon"><span><strong>Anonymous submissions</strong><small>Hide the author from the public suggestion card.</small></span><input id="suggest-anon" type="checkbox" checked={suggestions.anonymous ?? false} onChange={(event) => updateSuggestions({ anonymous: event.target.checked })} /></label><label className="switch-row" htmlFor="suggest-threads"><span><strong>Discussion threads</strong><small>Create a thread beside every new suggestion.</small></span><input id="suggest-threads" type="checkbox" checked={suggestions.createThreads ?? true} onChange={(event) => updateSuggestions({ createThreads: event.target.checked })} /></label></div><div className="mini-discord-card"><span className="mini-card-number">Suggestion #42</span><strong>A better weekly event format</strong><p>Members vote with 👍 or 👎, then staff publish a decision.</p><div><span>👍 18</span><span>👎 2</span><span className="decision-chip">Approved</span></div></div></section>

        <section className="settings-card community-card"><div className="feature-heading"><span className="feature-icon"><Star size={21} /></span><div><span className="page-kicker">Best of the server</span><h2>Starboard</h2></div></div><p>When a message crosses the reaction threshold, Onyx mirrors it once and keeps the score current.</p><div className="form-grid"><div className="field"><label htmlFor="star-channel">Highlight channel</label><select id="star-channel" className="select" value={starboard.channelId ?? ""} onChange={(event) => updateStarboard({ channelId: event.target.value || undefined })}><option value="">Choose a channel</option>{textChannels.map((channel) => <option key={channel.id} value={channel.id}>#{channel.name}</option>)}</select></div><div className="field"><label htmlFor="star-emoji">Reaction</label><input id="star-emoji" className="input" maxLength={64} value={starboard.emoji ?? "⭐"} onChange={(event) => updateStarboard({ emoji: event.target.value })} /></div><div className="field"><label htmlFor="star-threshold">Required reactions</label><input id="star-threshold" className="input" type="number" min={2} max={100} value={starboard.threshold ?? 3} onChange={(event) => updateStarboard({ threshold: Number(event.target.value) })} /></div></div><label className="switch-row" htmlFor="self-stars"><span><strong>Count self-reactions</strong><small>Let authors contribute to their own threshold.</small></span><input id="self-stars" type="checkbox" checked={starboard.allowSelfStars ?? false} onChange={(event) => updateStarboard({ allowSelfStars: event.target.checked })} /></label><div className="field"><label>Ignored channels</label><div className="channel-chip-grid">{textChannels.slice(0, 24).map((channel) => { const ignored = (starboard.ignoredChannelIds ?? []).includes(channel.id); return <button type="button" className={`channel-chip${ignored ? " selected" : ""}`} key={channel.id} onClick={() => updateStarboard({ ignoredChannelIds: ignored ? (starboard.ignoredChannelIds ?? []).filter((id) => id !== channel.id) : [...(starboard.ignoredChannelIds ?? []), channel.id].slice(0, 50) })}>#{channel.name}{ignored && <Check size={12} />}</button>; })}</div></div><div className="star-preview"><span className="star-count">{starboard.emoji} {starboard.threshold}</span><div><strong>That message everyone keeps quoting</strong><span>Promoted once the reaction threshold is met.</span></div></div></section>
      </div>
      <div className="sticky-save-bar"><div><span className={`save-state-dot ${state.dirty ? "changed" : "saved"}`} /><strong>{state.dirty ? "Community setup has unsaved changes" : "Community setup is synced"}</strong></div><button className="button primary" onClick={() => void state.save()} disabled={!state.dirty || state.saving}>{state.saving ? "Saving…" : <><Check size={15} /> Save community setup</>}</button></div>
    </>}
  </DashboardShell>;
}
